# seal.sh - provision and audit the work boundary, PER PROFILE. The mechanism is
# generic (a host provisioner may drive it, or it runs standalone). Sourced by
# bin/severance after common.sh.
#
# Reads the severance profiles and makes each enclave's boundary real:
#   - the profile group exists (and the login user is NOT a permanent member)
#   - the work_dir GATE is sealed root:<group> 2770 + default ACL -- that one
#     directory is the whole wall; the children are left to the dev to own
#   - the enclave CLAUDE.md (SEVERANCE_ENCLAVE_MD) is placed in work_dir so
#     agents/humans there work with the ownership model, not against it
#   - NO passwordless `work` grant (any legacy one is removed): entering work is
#     a deliberate human sudo prompt, so an agent cannot silently cross the wall
#   - the git includeIf fragment carries one block per profile (gitdir from
#     work_dir -> ~/.config/git/<group>.inc); group-named so it generalizes to a
#     second enclave

USER_NAME=$(id -un)
SUDOERS=${SUDOERS:-/etc/sudoers.d/work-guard}   # legacy grant, removed if found
GIT_GEN=${GIT_GEN:-$HOME/.config/git/work-context.gen}
SCAN_ROOT=${SCAN_ROOT:-$HOME/src}

# Per-tool credential dirs live UNDER the enclave config root
# (WORK_HOME/.config/<tool>) so every work credential store shares the one
# work_dir-gate seal instead of N scattered ~/.config/*-<group> dirs
# (docs/work-home.md). WHICH tools, and which of them are explicitly sealed
# belt-and-braces, is the TABLE (share/tools + tools.d drop-ins), not a list
# hardcoded here -- adding a tool is a line of data.

# The login user must NOT be a permanent group member (the transient invariant).
_permanent_member() {
  getent group "$WC_GROUP" 2>/dev/null | cut -d: -f4 | tr ',' '\n' \
    | grep -qx "$USER_NAME"
}

# One git fragment, one block per profile: safe.directory + a gitdir includeIf
# pointing at the profile's identity (~/.config/git/<group>.inc). Iterates its
# OWN wc_load, so call it OUTSIDE a per-profile loop (it clobbers WC_*).
render_git_gen() {
  printf '# generated by work-guard from self/profiles; do not edit.\n'
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    wd=$(readlink -f "$WC_DIR" 2>/dev/null || printf '%s' "$WC_DIR")
    printf '[safe]\n'
    printf '\tdirectory = %s\n' "$wd"
    printf '\tdirectory = %s/*\n' "$wd"
    # carveout/ (the exempt personal-project group) sits two levels deep, which
    # the one-level %s/* glob above does not reach; cover it explicitly. Belt-
    # and-braces: these repos are login-user-owned, so dubious-ownership never
    # actually fires -- this just keeps it robust if that ever changes.
    printf '\tdirectory = %s/carveout/*\n' "$wd"
    printf '[includeIf "gitdir:%s/"]\n' "$wd"
    printf '\tpath = ~/.config/git/%s.inc\n' "$WC_GROUP"
  done
}

# repo-sync audit for the CURRENT profile: a repo whose remote matches the
# profile glob must live inside its work_dir, and vice versa, minus the
# sanctioned enclave-personal allowlist. One line per offender, none when clean.
_enclave_ok() {   # <repo-path>: on the sanctioned personal list?
  _rel=${1#"$WC_DIR"/}
  for _g in $WC_ENCLAVE_PERSONAL; do
    case "$_rel" in $_g) return 0 ;; esac
  done
  return 1
}
audit_repos() {
  [ -d "$SCAN_ROOT" ] || return 0
  find "$SCAN_ROOT" -type d -name .git 2>/dev/null | while IFS= read -r g; do
    repo=${g%/.git}
    # SKIP severance's own config root (work_dir/.config). That tree is TOOL
    # STATE this design put inside the seal on purpose, not source anyone
    # placed across the boundary, and tools keep git-backed caches in it --
    # claude's plugin marketplaces clone a public repo there today, gemini and
    # codex plausibly tomorrow. Each would report as a personal repo in the
    # work tree and each would be wrong.
    #
    # Structural, not a per-profile carve-out: enclave_personal exists for
    # SOURCE trees a human deliberately kept in the enclave, and listing a
    # derived path there would make every profile repeat the same exception.
    case "$repo/" in "$WC_CONFIG_ROOT"/*) continue ;; esac
    url=$(git -C "$repo" config --get remote.origin.url 2>/dev/null || true)
    case "$url" in $WC_GIT_REMOTE_GLOB) is_work=1 ;; *) is_work=0 ;; esac
    case "$repo/" in "$WC_DIR"/*) in_tree=1 ;; *) in_tree=0 ;; esac
    if   [ "$is_work" = 1 ] && [ "$in_tree" = 0 ]; then
      echo "$WC_PROFILE: work-remote repo outside work_dir: $repo"
    elif [ "$is_work" = 0 ] && [ "$in_tree" = 1 ]; then
      _enclave_ok "$repo" \
        || echo "$WC_PROFILE: personal-remote repo inside work_dir: $repo"
    fi
  done
}


# Seal an identity dir the same way as the work_dir gate: root-owned, 2770
# (personal denied at traversal), + a default ACL new entries inherit. So a corp
# credential dir lives behind the SAME kernel wall as the tree. Sealed only when
# the owning tool is present (its shim makes `command -v` true on such a box).
_seal_identity_dir() {   # <dir>
  sudo mkdir -p "$1"
  sudo chown "root:$WC_GROUP" "$1"
  # 0-PREFIXED on purpose: for a DIRECTORY, coreutils chmod PRESERVES inherited
  # setuid/setgid bits under a bare numeric mode, so `chmod 2770` on a dir made
  # inside a setgid parent (a .config under the setgid gate) keeps the inherited
  # setuid -> 6770. The explicit leading zero clears the high bits, so every
  # sealed dir is canonically 2770 whatever its parent. (Symbolic u-s works.)
  sudo chmod 02770 "$1"
  sudo setfacl -d -m g:"$WC_GROUP":rwX -m o::--- "$1"
  echo "severance: $1 sealed (root:$WC_GROUP 2770 + default ACL)"
}
# Seal every table row marked `yes` whose tool is actually installed. Absent
# tool -> skipped: the right thing happens if the crumbs are there, and nothing
# happens if they are not.
seal_tool_dirs() {
  wc_tools | while read -r _tool _env _dir _seal; do
    [ "$_seal" = yes ] || continue
    command -v "$_tool" >/dev/null 2>&1 || continue
    _seal_identity_dir "$WC_CONFIG_ROOT/$_dir"
  done
}

# The sealed per-enclave CONFIG ROOT: WORK_HOME/.config (WORK_HOME = work_dir).
# Per-tool work state -- agent configs, a credential pool, the corp
# creds -- migrates under here so ONE seal (the work_dir gate) protects every
# credential store, not N scattered dirs. Sealed explicitly (belt-and-braces);
# the gate's traversal denial is what actually keeps a same-uid personal process
# out, so inner state stays safe whatever its owner. See docs/work-home.md.
# Test-override.
_workhome_config() { echo "${WORKHOME_CONFIG:-$WC_DIR/.config}"; }
seal_workhome_config() { _seal_identity_dir "$(_workhome_config)"; }

# SEED a generic enclave note into a FRESH enclave. Source is
# SEVERANCE_ENCLAVE_MD (default: the package's generic, tool-agnostic note). The
# enclave then OWNS its CLAUDE.md: we NEVER clobber an existing one (a project's
# own guidance, or edits that de-generalize it, must survive). So this is
# place-if-absent only, not a managed file.
place_claude_md() {
  _src=${SEVERANCE_ENCLAVE_MD:-$SEVERANCE_SHARE/enclave/CLAUDE.md}
  [ -f "$_src" ] || return 0
  _dst=$WC_DIR/CLAUDE.md
  if sudo test -e "$_dst"; then
    echo "severance: enclave CLAUDE.md present ($WC_PROFILE); left as-is"
  else
    sudo install -m 0644 -o root -g "$WC_GROUP" "$_src" "$_dst"
    echo "severance: seeded enclave CLAUDE.md in $WC_DIR"
  fi
}

# Provision the CURRENT profile's boundary (WC_* set by wc_load).
_guard_one() {
  echo "severance: applying '$WC_PROFILE' (group $WC_GROUP)"
  getent group "$WC_GROUP" >/dev/null 2>&1 || sudo groupadd "$WC_GROUP"
  echo "severance: group '$WC_GROUP' present"
  if _permanent_member; then
    echo "severance: REFUSING - $USER_NAME is a PERMANENT member of" >&2
    echo "  '$WC_GROUP' (gpasswd -d $USER_NAME $WC_GROUP). The group must" >&2
    echo "  be transient or the personal guard breaks." >&2
    exit 1
  fi
  # Seal the GATE (this dir IS the wall): root-owned (login user cannot chmod it
  # open), 2770, + a default ACL new entries inherit. Leave the children to the
  # dev to own (their pnpm/git chmod their own files).
  sudo mkdir -p "$WC_DIR"
  sudo chown "root:$WC_GROUP" "$WC_DIR"
  sudo chmod 02770 "$WC_DIR"   # 0-prefixed: clear inherited setuid (see above)
  sudo setfacl -d -m g:"$WC_GROUP":rwX -m o::--- "$WC_DIR"
  echo "severance: work_dir gate sealed (root:$WC_GROUP 2770 + default ACL)"
  seal_workhome_config
  place_claude_md
  seal_tool_dirs
}

sev_seal() {
  _any=0
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    _any=1
    _guard_one
  done
  [ "$_any" = 1 ] || { echo "severance: no profiles; skipping" >&2; return 0; }

  # git fragment: one block per profile (render_git_gen iterates internally).
  mkdir -p "$(dirname "$GIT_GEN")"; render_git_gen > "$GIT_GEN"
  echo "severance: git fragment $GIT_GEN"

  # NO passwordless `work` grant. A blanket NOPASSWD on `work` let ANY login
  # process silently acquire the group -- turning the kernel wall into a rule
  # the model is trusted to honor. `work` now authorizes through the user's
  # sudo (a prompt an agent cannot supply). Remove any legacy grant.
  if sudo -n test -e "$SUDOERS" 2>/dev/null || [ -e "$SUDOERS" ]; then
    sudo rm -f "$SUDOERS" && echo "severance: removed legacy grant $SUDOERS"
  fi
  echo "severance: seal done"
}

# Audit a sealed identity dir that now lives INSIDE the gate (gcloud/gemini
# under WORK_HOME/.config): a plain login-user check cannot stat it, so try
# sudo -n and report UNVERIFIABLE rather than SILENTLY DROPPING the verdict (the
# blind spot when these moved behind the gate). <label> <dir>.
_check_sealed_dir() {
  _cl=$1 _cd=$2
  _co=$(sudo -n stat -c '%U:%G' "$_cd" 2>/dev/null \
        || stat -c '%U:%G' "$_cd" 2>/dev/null || echo '')
  if [ -z "$_co" ]; then
    if sudo -n true 2>/dev/null; then
      _ok "$_cl dir absent (sealed on apply)"      # can sudo, so truly absent
    else _ok "$_cl dir unverifiable here (need sudo cache/work group)"; fi
    return 0
  fi
  _cm=$(sudo -n stat -c '%a' "$_cd" 2>/dev/null \
        || stat -c '%a' "$_cd" 2>/dev/null || echo '?')
  _ca=$(sudo -n getfacl -p "$_cd" 2>/dev/null \
        || getfacl -p "$_cd" 2>/dev/null || true)
  if [ "$_co" = "root:$WC_GROUP" ]; then _ok "$_cl dir owner root:$WC_GROUP"
  else _bad "$_cl dir owner $_co, want root:$WC_GROUP"; fi
  if [ "$_cm" = 2770 ]; then _ok "$_cl dir mode 2770 (personal denied)"
  else _bad "$_cl dir mode ${_cm:-?}, want 2770"; fi
  if printf '%s\n' "$_ca" | grep -q "^default:other::---"; then
    _ok "$_cl dir default other ACL denies new entries"
  else _bad "$_cl dir default other ACL not '---' (creds may leak)"; fi
}

_seal_check_one() {
  echo "-- $WC_PROFILE (group $WC_GROUP) --"
  if getent group "$WC_GROUP" >/dev/null 2>&1; then
    _ok "group '$WC_GROUP' present"
  else _bad "group '$WC_GROUP' missing"; fi

  if _permanent_member; then
    _bad "$USER_NAME is a PERMANENT member of '$WC_GROUP' (must be transient)"
  else _ok "$USER_NAME not a permanent member of '$WC_GROUP'"; fi

  if [ -d "$WC_DIR" ]; then
    owner=$(stat -c '%U:%G' "$WC_DIR" 2>/dev/null || echo '?')
    mode=$(stat -c '%a' "$WC_DIR" 2>/dev/null || echo '?')
    _acl=$(getfacl -p "$WC_DIR" 2>/dev/null || true)
    if [ "$owner" = "root:$WC_GROUP" ]; then _ok "work_dir owner root:$WC_GROUP"
    else _bad "work_dir owner $owner, want root:$WC_GROUP"; fi
    if [ "$mode" = 2770 ]; then _ok "work_dir mode 2770 (the traversal gate)"
    else _bad "work_dir mode ${mode:-?}, want 2770 (other must be denied)"; fi
    if printf '%s\n' "$_acl" | grep -q "^default:group:$WC_GROUP:rwx"; then
      _ok "work_dir default group ACL for '$WC_GROUP'"
    else _bad "work_dir missing default group ACL for '$WC_GROUP'"; fi
    if printf '%s\n' "$_acl" | grep -q "^default:other::---"; then
      _ok "work_dir default other ACL denies new entries"
    else _bad "work_dir default other ACL not '---' (new entries may leak)"; fi
  else _ok "work_dir $WC_DIR absent (nothing to seal yet)"; fi

  # The sealed config root WORK_HOME/.config sits INSIDE the gate, so a plain
  # personal process cannot stat it (needs the sudo cache or the work group);
  # report unverifiable rather than crying false drift. See docs/work-home.md.
  if [ -d "$WC_DIR" ]; then
    _wc=$(_workhome_config)
    _wo=$(sudo -n stat -c '%U:%G' "$_wc" 2>/dev/null \
          || stat -c '%U:%G' "$_wc" 2>/dev/null || echo '')
    _wm=$(sudo -n stat -c '%a' "$_wc" 2>/dev/null \
          || stat -c '%a' "$_wc" 2>/dev/null || echo '')
    if [ -n "$_wo" ]; then
      if [ "$_wo" = "root:$WC_GROUP" ] && [ "$_wm" = 2770 ]; then
        _ok "config root .config sealed (root:$WC_GROUP 2770)"
      else
        _bad "config root .config $_wo mode $_wm, want root:$WC_GROUP 2770"
      fi
    elif sudo -n true 2>/dev/null; then
      _bad "config root $_wc absent (re-run apply)"
    else _ok "config root .config unverifiable here (need sudo cache/group)"; fi
  fi

  wc_tools | while read -r _tool _env _dir _seal; do
    [ "$_seal" = yes ] || continue
    command -v "$_tool" >/dev/null 2>&1 || continue
    _check_sealed_dir "$_tool" "$WC_CONFIG_ROOT/$_dir"
  done

  # The enclave OWNS its CLAUDE.md (seed-only); verify presence, never content.
  if [ -d "$WC_DIR" ]; then
    _dst=$WC_DIR/CLAUDE.md
    if sudo -n test -e "$_dst" 2>/dev/null || [ -e "$_dst" ]; then
      _ok "enclave CLAUDE.md present (enclave-owned)"
    elif sudo -n true 2>/dev/null; then
      _ok "enclave CLAUDE.md absent (seeded on apply)"
    else
      _ok "enclave CLAUDE.md unverifiable here (need sudo cache/work group)"
    fi
  fi

  if [ -n "$WC_ENCLAVE_PERSONAL" ]; then
    _ok "sanctioned personal repos in work_dir: $WC_ENCLAVE_PERSONAL"
  fi


  findings=$(audit_repos)
  if [ -n "$findings" ]; then
    tmp=$(mktemp); printf '%s\n' "$findings" > "$tmp"
    while IFS= read -r f; do [ -n "$f" ] && _bad "$f"; done < "$tmp"
    rm -f "$tmp"
  else _ok "repos consistent (remote glob matches work tree)"; fi
}

sev_seal_check() {
  echo "== severance seal (per-profile boundary) =="
  _any=0
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    _any=1
    _seal_check_one
  done
  [ "$_any" = 1 ] || _ok "no profiles provisioned (personal-only box)"

  # git fragment carries every profile's block (render_git_gen iterates).
  if [ -f "$GIT_GEN" ] && cmp -s "$GIT_GEN" - <<GEN
$(render_git_gen)
GEN
  then _ok "git fragment current"
  else _bad "git fragment $GIT_GEN stale or missing (re-run apply)"; fi

  # The blanket passwordless `work` grant must NOT exist (a legacy box may still
  # carry it). /etc/sudoers.d is 0750, so verify via sudo -n; cry drift only
  # when we HAVE the privilege to look and it is STILL PRESENT.
  if sudo -n test -e "$SUDOERS" 2>/dev/null; then
    _bad "legacy passwordless grant $SUDOERS present (re-run apply to remove)"
  elif sudo -n true 2>/dev/null || [ ! -e "$SUDOERS" ]; then
    _ok "no passwordless work grant (entering work is a human sudo gate)"
  else
    _ok "sudoers state unverifiable here (need sudo cache)"
  fi
}
