# seal.sh - provision and audit the work boundary, PER PROFILE. Ported from
# tackup's modules/work-guard (the mechanism is generic; tackup was only its
# first driver). Sourced by bin/severance after common.sh.
#
# Reads the severance profiles and makes each enclave's boundary real:
#   - the profile group exists (and the login user is NOT a permanent member)
#   - the work_dir GATE is sealed root:<group> 2770 + default ACL -- that one
#     directory is the whole wall; the children are left to the dev to own
#   - the enclave CLAUDE.md (SEVERANCE_ENCLAVE_MD) is placed in work_dir so
#     agents/humans there work with the ownership model, not against it
#   - any declared service overlay is re-owned to <service_user>:<group> right
#     after the seal (a rootless service reaches its bind mounts by owner, not
#     group; group access does not cross the user namespace)
#   - NO passwordless `work` grant (any legacy one is removed): entering work is
#     a deliberate human sudo prompt, so an agent cannot silently cross the wall
#   - the git includeIf fragment carries one block per profile (gitdir from
#     work_dir -> ~/.config/git/<group>.inc); group-named so it generalizes to a
#     second enclave

USER_NAME=$(id -un)
SUDOERS=${SUDOERS:-/etc/sudoers.d/work-guard}   # legacy grant, removed if found
GIT_GEN=${GIT_GEN:-$HOME/.config/git/work-context.gen}
SCAN_ROOT=${SCAN_ROOT:-$HOME/src}

# The WORK corp-Google identity dirs, keyed on the profile group (manifest's
# group `manifest` -> ~/.config/{gcloud,gemini}-manifest, matching valet-key's
# adapters). Sealed like the work_dir gate so corp creds are kernel-protected,
# not merely env-selected. gemini's GEMINI_CLI_HOME points at its dir
# (valet-key's
# dirs override) and stores .gemini/ inside, inheriting the seal. Test-override.
_gcloud_dir() { echo "${GCLOUD_WORK:-$HOME/.config/gcloud-$WC_GROUP}"; }
_gemini_dir() { echo "${GEMINI_WORK:-$HOME/.config/gemini-$WC_GROUP}"; }

# The login user must NOT be a permanent group member (the transient invariant).
_permanent_member() {
  getent group "$WC_GROUP" 2>/dev/null | cut -d: -f4 | tr ',' '\n' \
    | grep -qx "$USER_NAME"
}

# One git fragment, one block per profile: safe.directory + a gitdir includeIf
# pointing at the profile's identity (~/.config/git/<group>.inc). Iterates its
# OWN wc_load, so call it OUTSIDE a per-profile loop (it clobbers WC_*).
render_git_gen() {
  printf '# generated by work-guard from self/profiles; do not edit.\n'
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    wd=$(readlink -f "$WC_DIR" 2>/dev/null || printf '%s' "$WC_DIR")
    printf '[safe]\n'
    printf '\tdirectory = %s\n' "$wd"
    printf '\tdirectory = %s/*\n' "$wd"
    # carveout/ (the exempt personal-project group) sits two levels deep, which
    # the one-level %s/* glob above does not reach; cover it explicitly. Belt-
    # and-braces: these repos are login-user-owned, so dubious-ownership never
    # actually fires -- this just keeps it robust if that ever changes.
    printf '\tdirectory = %s/carveout/*\n' "$wd"
    printf '[includeIf "gitdir:%s/"]\n' "$wd"
    printf '\tpath = ~/.config/git/%s.inc\n' "$WC_GROUP"
  done
}

# repo-sync audit for the CURRENT profile: a repo whose remote matches the
# profile glob must live inside its work_dir, and vice versa, minus the
# sanctioned enclave-personal allowlist. One line per offender, none when clean.
_enclave_ok() {   # <repo-path>: on the sanctioned personal list?
  _rel=${1#"$WC_DIR"/}
  for _g in $WC_ENCLAVE_PERSONAL; do
    case "$_rel" in $_g) return 0 ;; esac
  done
  return 1
}
audit_repos() {
  [ -d "$SCAN_ROOT" ] || return 0
  find "$SCAN_ROOT" -type d -name .git 2>/dev/null | while IFS= read -r g; do
    repo=${g%/.git}
    url=$(git -C "$repo" config --get remote.origin.url 2>/dev/null || true)
    case "$url" in $WC_GIT_REMOTE_GLOB) is_work=1 ;; *) is_work=0 ;; esac
    case "$repo/" in "$WC_DIR"/*) in_tree=1 ;; *) in_tree=0 ;; esac
    if   [ "$is_work" = 1 ] && [ "$in_tree" = 0 ]; then
      echo "$WC_PROFILE: work-remote repo outside work_dir: $repo"
    elif [ "$is_work" = 0 ] && [ "$in_tree" = 1 ]; then
      _enclave_ok "$repo" \
        || echo "$WC_PROFILE: personal-remote repo inside work_dir: $repo"
    fi
  done
}

# Service-overlay ACL. A rootless-container service reaches its bind-mounted
# work files across the user namespace by OWNER identity or a named-user ACL
# (matched on the container's host uid) -- a supplementary group like `work`
# does not cross it -- so a work file the container does not own read-denies it
# every run. Restore access with a named-user ACL (access AND DEFAULT) for the
# service user, applied right after the seal. The default entry is inherited, so
# a file written LATER by any user is born service-reachable -- this is what
# survives an edit, where owner does not.
grant_overlay_acl() {   # <perms> <rel-path>; sets _done
  _p=$WC_DIR/$2
  # Test existence AS ROOT: the tree is sealed root:<group> 2770, so the
  # unprivileged user running this cannot traverse in and would read every
  # path as absent -- silently skipping the grant (asserted!=real).
  if ! sudo test -e "$_p"; then
    echo "severance: service overlay '$_p' absent; skip" >&2
    return 0
  fi
  sudo setfacl -R    -m u:"$WC_SERVICE_USER":"$1" "$_p"
  sudo setfacl -R -d -m u:"$WC_SERVICE_USER":"$1" "$_p"
  if ! sudo getfacl -p "$_p" 2>/dev/null \
       | grep -q "^user:$WC_SERVICE_USER:"; then
    echo "severance: service ACL for '$_p' did not stick" >&2
    exit 1
  fi
  _done=1
}
seal_service_overlay() {
  [ -n "$WC_SERVICE_USER" ] || return 0
  [ -n "$WC_SERVICE_OVERLAY$WC_SERVICE_OVERLAY_WRITE" ] || return 0
  if ! id "$WC_SERVICE_USER" >/dev/null 2>&1; then
    echo "severance: service user '$WC_SERVICE_USER' absent (run runner);" >&2
    echo "  overlay ACL not granted" >&2
    return 0
  fi
  _done=0
  for _rel in $WC_SERVICE_OVERLAY; do grant_overlay_acl rX "$_rel"; done
  for _rel in $WC_SERVICE_OVERLAY_WRITE; do
    grant_overlay_acl rwX "$_rel"
  done
  [ "$_done" = 1 ] && echo \
    "severance: service overlay ACL granted (u:$WC_SERVICE_USER)"
  return 0
}

# Seal an identity dir the same way as the work_dir gate: root-owned, 2770
# (personal denied at traversal), + a default ACL new entries inherit. So a corp
# credential dir lives behind the SAME kernel wall as the tree. Sealed only when
# the owning tool is present (its shim makes `command -v` true on such a box).
_seal_identity_dir() {   # <dir>
  sudo mkdir -p "$1"
  sudo chown "root:$WC_GROUP" "$1"
  sudo chmod 2770 "$1"
  sudo setfacl -d -m g:"$WC_GROUP":rwX -m o::--- "$1"
  echo "severance: $1 sealed (root:$WC_GROUP 2770 + default ACL)"
}
seal_gcloud_work() {
  command -v gcloud >/dev/null 2>&1 || return 0
  _seal_identity_dir "$(_gcloud_dir)"
}
seal_gemini_home() {
  command -v gemini >/dev/null 2>&1 || return 0
  _seal_identity_dir "$(_gemini_dir)"
}

# SEED a generic enclave note into a FRESH enclave. Source is
# SEVERANCE_ENCLAVE_MD (default: the package's generic, tool-agnostic note). The
# enclave then OWNS its CLAUDE.md: we NEVER clobber an existing one (a project's
# own guidance, or edits that de-generalize it, must survive). So this is
# place-if-absent only, not a managed file.
place_claude_md() {
  _src=${SEVERANCE_ENCLAVE_MD:-$SEVERANCE_SHARE/enclave/CLAUDE.md}
  [ -f "$_src" ] || return 0
  _dst=$WC_DIR/CLAUDE.md
  if sudo test -e "$_dst"; then
    echo "severance: enclave CLAUDE.md present ($WC_PROFILE); left as-is"
  else
    sudo install -m 0644 -o root -g "$WC_GROUP" "$_src" "$_dst"
    echo "severance: seeded enclave CLAUDE.md in $WC_DIR"
  fi
}

# Provision the CURRENT profile's boundary (WC_* set by wc_load).
_guard_one() {
  echo "severance: applying '$WC_LABEL' (group $WC_GROUP)"
  getent group "$WC_GROUP" >/dev/null 2>&1 || sudo groupadd "$WC_GROUP"
  echo "severance: group '$WC_GROUP' present"
  if _permanent_member; then
    echo "severance: REFUSING - $USER_NAME is a PERMANENT member of" >&2
    echo "  '$WC_GROUP' (gpasswd -d $USER_NAME $WC_GROUP). The group must" >&2
    echo "  be transient or the personal guard breaks." >&2
    exit 1
  fi
  # Seal the GATE (this dir IS the wall): root-owned (login user cannot chmod it
  # open), 2770, + a default ACL new entries inherit. Leave the children to the
  # dev to own (their pnpm/git chmod their own files).
  sudo mkdir -p "$WC_DIR"
  sudo chown "root:$WC_GROUP" "$WC_DIR"
  sudo chmod 2770 "$WC_DIR"
  sudo setfacl -d -m g:"$WC_GROUP":rwX -m o::--- "$WC_DIR"
  echo "severance: work_dir gate sealed (root:$WC_GROUP 2770 + default ACL)"
  place_claude_md
  seal_gcloud_work
  seal_gemini_home
  seal_service_overlay
}

sev_seal() {
  _any=0
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    _any=1
    _guard_one
  done
  [ "$_any" = 1 ] || { echo "severance: no profiles; skipping" >&2; return 0; }

  # git fragment: one block per profile (render_git_gen iterates internally).
  mkdir -p "$(dirname "$GIT_GEN")"; render_git_gen > "$GIT_GEN"
  echo "severance: git fragment $GIT_GEN"

  # NO passwordless `work` grant. A blanket NOPASSWD on `work` let ANY login
  # process silently acquire the group -- turning the kernel wall into a rule
  # the model is trusted to honor. `work` now authorizes through the user's
  # sudo (a prompt an agent cannot supply). Remove any legacy grant.
  if sudo -n test -e "$SUDOERS" 2>/dev/null || [ -e "$SUDOERS" ]; then
    sudo rm -f "$SUDOERS" && echo "severance: removed legacy grant $SUDOERS"
  fi
  echo "severance: seal done"
}

_seal_check_one() {
  echo "-- $WC_LABEL (group $WC_GROUP) --"
  if getent group "$WC_GROUP" >/dev/null 2>&1; then
    _ok "group '$WC_GROUP' present"
  else _bad "group '$WC_GROUP' missing"; fi

  if _permanent_member; then
    _bad "$USER_NAME is a PERMANENT member of '$WC_GROUP' (must be transient)"
  else _ok "$USER_NAME not a permanent member of '$WC_GROUP'"; fi

  if [ -d "$WC_DIR" ]; then
    owner=$(stat -c '%U:%G' "$WC_DIR" 2>/dev/null || echo '?')
    mode=$(stat -c '%a' "$WC_DIR" 2>/dev/null || echo '?')
    _acl=$(getfacl -p "$WC_DIR" 2>/dev/null || true)
    if [ "$owner" = "root:$WC_GROUP" ]; then _ok "work_dir owner root:$WC_GROUP"
    else _bad "work_dir owner $owner, want root:$WC_GROUP"; fi
    if [ "$mode" = 2770 ]; then _ok "work_dir mode 2770 (the traversal gate)"
    else _bad "work_dir mode ${mode:-?}, want 2770 (other must be denied)"; fi
    if printf '%s\n' "$_acl" | grep -q "^default:group:$WC_GROUP:rwx"; then
      _ok "work_dir default group ACL for '$WC_GROUP'"
    else _bad "work_dir missing default group ACL for '$WC_GROUP'"; fi
    if printf '%s\n' "$_acl" | grep -q "^default:other::---"; then
      _ok "work_dir default other ACL denies new entries"
    else _bad "work_dir default other ACL not '---' (new entries may leak)"; fi
  else _ok "work_dir $WC_DIR absent (nothing to seal yet)"; fi

  _gc=$(_gcloud_dir)
  if command -v gcloud >/dev/null 2>&1 && [ -d "$_gc" ]; then
    _go=$(stat -c '%U:%G' "$_gc" 2>/dev/null || echo '?')
    _gm=$(stat -c '%a' "$_gc" 2>/dev/null || echo '?')
    _ga=$(getfacl -p "$_gc" 2>/dev/null || true)
    if [ "$_go" = "root:$WC_GROUP" ]; then _ok "gcloud dir owner root:$WC_GROUP"
    else _bad "gcloud dir owner $_go, want root:$WC_GROUP"; fi
    if [ "$_gm" = 2770 ]; then _ok "gcloud dir mode 2770 (personal denied)"
    else _bad "gcloud dir mode ${_gm:-?}, want 2770"; fi
    if printf '%s\n' "$_ga" | grep -q "^default:other::---"; then
      _ok "gcloud dir default other ACL denies new entries"
    else _bad "gcloud dir default other ACL not '---' (creds may leak)"; fi
  fi

  _ge=$(_gemini_dir)
  if command -v gemini >/dev/null 2>&1 && [ -d "$_ge" ]; then
    _eo=$(stat -c '%U:%G' "$_ge" 2>/dev/null || echo '?')
    _em=$(stat -c '%a' "$_ge" 2>/dev/null || echo '?')
    _ea=$(getfacl -p "$_ge" 2>/dev/null || true)
    if [ "$_eo" = "root:$WC_GROUP" ]; then _ok "gemini dir owner root:$WC_GROUP"
    else _bad "gemini dir owner $_eo, want root:$WC_GROUP"; fi
    if [ "$_em" = 2770 ]; then _ok "gemini dir mode 2770 (personal denied)"
    else _bad "gemini dir mode ${_em:-?}, want 2770"; fi
    if printf '%s\n' "$_ea" | grep -q "^default:other::---"; then
      _ok "gemini dir default other ACL denies new entries"
    else _bad "gemini dir default other ACL not '---' (creds may leak)"; fi
  fi

  # The enclave OWNS its CLAUDE.md (seed-only); verify presence, never content.
  if [ -d "$WC_DIR" ]; then
    _dst=$WC_DIR/CLAUDE.md
    if sudo -n test -e "$_dst" 2>/dev/null || [ -e "$_dst" ]; then
      _ok "enclave CLAUDE.md present (enclave-owned)"
    elif sudo -n true 2>/dev/null; then
      _ok "enclave CLAUDE.md absent (seeded on apply)"
    else
      _ok "enclave CLAUDE.md unverifiable here (need sudo cache/work group)"
    fi
  fi

  if [ -n "$WC_ENCLAVE_PERSONAL" ]; then
    _ok "sanctioned personal repos in work_dir: $WC_ENCLAVE_PERSONAL"
  fi

  if [ -n "$WC_SERVICE_USER" ] \
     && [ -n "$WC_SERVICE_OVERLAY$WC_SERVICE_OVERLAY_WRITE" ]; then
    _seen=0 _bad_ov=
    for _rel in $WC_SERVICE_OVERLAY $WC_SERVICE_OVERLAY_WRITE; do
      _f=$(sudo -n getfacl -p "$WC_DIR/$_rel" 2>/dev/null \
           || getfacl -p "$WC_DIR/$_rel" 2>/dev/null) || continue
      _seen=1
      printf '%s\n' "$_f" | grep -q "^user:$WC_SERVICE_USER:" \
        || _bad_ov="$_bad_ov $_rel"
    done
    if [ "$_seen" = 0 ]; then
      _ok "service overlay ACL unverifiable here (need work group)"
    elif [ -n "$_bad_ov" ]; then
      _bad "service overlay missing $WC_SERVICE_USER ACL:$_bad_ov"
    else _ok "service overlay grants $WC_SERVICE_USER via named-user ACL"; fi
  fi

  findings=$(audit_repos)
  if [ -n "$findings" ]; then
    tmp=$(mktemp); printf '%s\n' "$findings" > "$tmp"
    while IFS= read -r f; do [ -n "$f" ] && _bad "$f"; done < "$tmp"
    rm -f "$tmp"
  else _ok "repos consistent (remote glob matches work tree)"; fi
}

sev_seal_check() {
  echo "== severance seal (per-profile boundary) =="
  _any=0
  for _p in $(wc_profiles); do
    wc_load "$_p" || continue
    _any=1
    _seal_check_one
  done
  [ "$_any" = 1 ] || _ok "no profiles provisioned (personal-only box)"

  # git fragment carries every profile's block (render_git_gen iterates).
  if [ -f "$GIT_GEN" ] && cmp -s "$GIT_GEN" - <<GEN
$(render_git_gen)
GEN
  then _ok "git fragment current"
  else _bad "git fragment $GIT_GEN stale or missing (re-run apply)"; fi

  # The blanket passwordless `work` grant must NOT exist (a legacy box may still
  # carry it). /etc/sudoers.d is 0750, so verify via sudo -n; cry drift only
  # when we HAVE the privilege to look and it is STILL PRESENT.
  if sudo -n test -e "$SUDOERS" 2>/dev/null; then
    _bad "legacy passwordless grant $SUDOERS present (re-run apply to remove)"
  elif sudo -n true 2>/dev/null || [ ! -e "$SUDOERS" ]; then
    _ok "no passwordless work grant (entering work is a human sudo gate)"
  else
    _ok "sudoers state unverifiable here (need sudo cache)"
  fi
}
